### ISSUE TITLE
No line break between dialog and action in preview

### ISSUE THREAD

**Issue by captaindooley** [superlou/fountain-atom#13] opened 2017-06-27 19:03 UTC
Not a major issue, since I have to generate a proper PDF elsewhere, but when I preview there is no line break shown between dialog and action. Is this systemic or is it just me?

**Comment by superlou** [comment] 2017-06-27 21:04
I'm able to reproduce it with the following:

```
INT. HOUSE

This is some descriptive text.

RONALD
This text was long enough that it caused things to wrap-around.

Then the action text happened, but it was right against the dialogue.
```

It looks like there should be padding at the end of dialogue.  To match the other padding that's in here, `.fountain-preview .page div.dialogue p` should have `margin-bottom: 15px;`.

**Comment by superlou** [comment] 2017-06-27 21:09
@captaindooley To test this, open your custom stylesheet using File --> Stylesheet... from the menu bar.  Add this to the end:

.fountain-preview .page div.dialogue p {
  margin-bottom: 15px;
}

If that works, I'll see if I can update the package so you don't need the custom stylesheet tweak.  I couldn't find a good example of a detailed screenplay format when I started this, so there are lots of little inconsistencies like this bug.

**Comment by captaindooley** [comment] 2017-06-27 21:30
That seems to work and doesn't cause any other issues that I can see in my current script.

**Comment by superlou** [comment] 2017-06-28 00:06
If you update to v0.5.5, it should be working and you can remove the custom stylesheet hack (as well as work nicely with parentheticals on their own line).  Let me know if it works.

**Comment by superlou** [comment] 2017-07-18 12:58
@captaindooley I'm going to close this.  If you are still receiving the issue, please reopen.

**Closed by superlou** 2017-07-18 12:58 UTC
