### ISSUE TITLE
Page breaks show up as synopses

### ISSUE THREAD

**Issue by DaTedinator** [superlou/fountain-atom#93] opened 2019-12-20 17:27 UTC
Took me a while to realize why a seemingly random one of my headers would get a "==" synopsis underneath it; I have a page break (signified by three equals - "===") at one point in my script, and the outline is interpreting that as a synopsis of two equals signs.

**Comment by superlou** [comment] 2019-12-20 18:10
Can you provide a short script that causes this issue?

**Comment by DaTedinator** [comment] 2019-12-20 18:29
Sure thing.

![image](https://user-images.githubusercontent.com/29130403/71281604-2debcb80-2313-11ea-8838-a7992b68a9a3.png)

Text to copy/paste:

```
#Section 1
=Steve washes his car

FADE IN:

INT. CAR WASH

STEVE washes his car.

STEVE
Boy I love washing my car blah blah blah.

He drops dead.

===

#Section 2
=The funeral

INT. FUNERAL PARLOR

The MINISTER delivers a eulogy.

MINISTER
He died doing what he loved: washing his car.

THE END
```

**Comment by superlou** [comment] 2019-12-21 20:55
Don't worry about it, and no snark perceived. Having a minimal test case that demonstrates the problem is one of the most important things in bug fixing. This should be fixed in the latest release, 0.8.2. Please close the issue if it works on your side.

**Comment by DaTedinator** [comment] 2019-12-21 23:12
Unfortunately, it still seems to be occurring. I tried uninstalling and reinstalling the package too, just to be sure. Let me know if there's any other info I can give you.

**Comment by superlou** [comment] 2019-12-21 23:14
Interesting. Can you confirm you have version 0.8.2? Is your page break line exactly `===`, no spaces at the end?

**Comment by DaTedinator** [comment] 2019-12-21 23:17
Yeah, it's 0.8.2, and no spaces. And if I make a new file and paste in the example I gave above, I'm seeing the exact same thing.

**Comment by superlou** [comment] 2019-12-21 23:20
That's really odd. This is what it looks like on mine with 0.8.2 installed:

![image](https://user-images.githubusercontent.com/709695/71314858-92e01800-241e-11ea-885f-76b1cdf7cd6c.png)

**Comment by DaTedinator** [comment] 2019-12-21 23:28
That is weird. I tried rebooting and I tried a second computer and it's still happening. 

Why do your three equals signs merge together like that? Mine look like:
![image](https://user-images.githubusercontent.com/29130403/71314896-5accdb00-2406-11ea-8108-6dfcacb737de.png)

But yours are:
![image](https://user-images.githubusercontent.com/29130403/71314899-691af700-2406-11ea-8ec2-26ae1a54ae75.png)
 Could that have anything to do with the problem? Do I not have some setting enabled somewhere?

**Comment by superlou** [comment] 2019-12-21 23:34
That's just a ligature from the [Firacode](https://github.com/tonsky/FiraCode) font I have installed. It shouldn't affect anything.

**Comment by DaTedinator** [comment] 2019-12-21 23:46
Gotcha. Well, let me know if there's anything else I can do to help. I'm trying to think what else could matter. Both computers I tried were on the latest version of Windows 10 (Build 18362), both have all their packages updated, both are relatively recent installs of Atom. On the one computer literally the only community packages are this and the required pdf-view.

If all else fails, it's certainly not a workflow-breaking bug, I can live with it.

**Comment by superlou** [comment] 2019-12-23 20:43
That's really odd. If you look at your installed packages, it definitely say version 0.8.2? I just tried it on a Chromebook (in Crouton) and it works fine there. I can see synopses in the outline, but if there are exactly three equal signs, it isn't in the outline.

**Comment by DaTedinator** [comment] 2019-12-24 00:47
As far as I can tell, unless there's some other screen somewhere or box I have to check:

![image](https://user-images.githubusercontent.com/29130403/71386361-2b52d580-25a2-11ea-88d8-d7c3bf4276e7.png)

Is there any way there's some other package that's interfering with this? Maybe a package you have that I don't, maybe there's a package I need to disable? Some setting somewhere I need to turn off?

**Comment by superlou** [comment] 2019-12-26 23:30
There shouldn't be, and that looks like the right version. This is pretty weird. @jrbostic, any idea if there is some setting that might be causing @DaTedinator to not use the latest outline view module?

**Comment by jrbostic** [comment] 2019-12-27 17:44
@superlou The only thing that comes to mind is hidden characters, often added by Microsoft products and honored by other applications.  I've ran into that more than once at work with copying code from Word and Skype into an IDE. 

@DaTedinator Have you tried manually retyping the same script section to see if it parses differently?  Sometimes letters or spacing that look normal can have encoding that causes problems for parsers... Like what we rely on to find elements of a fountain script... So, I'd try and rule that out first.  Can you make this happen without copy/paste?

If it's not that, I'd have to take a closer look... At the grammar stuff... And the outline rendering.

**Comment by DaTedinator** [comment] 2019-12-28 21:21
Yeah, manually typing === gets the same result. 

I feel bad about all this trouble, I'm sure it's gonna wind up being me having missed something obvious or done something stupid.

**Comment by superlou** [comment] 2019-12-31 16:45
Don't worry about it. It's probably a bad assumption somewhere. @jrbostic did it behave as expected for you, or are you having the same issue as @DaTedinator?

**Comment by jrbostic** [comment] 2020-01-09 06:43
@superlou @DaTedinator  Just installed atom fresh on my Windows machine... added only the fountain-atom package... and this is verified reproducible.

**Comment by jrbostic** [comment] 2020-01-09 07:41
I see where the match is failing at line 195 of fountain-outline-view.coffee: `arr[i].match(/^===+$/)`.  The crazy thing is that arr[i] is "===", and it matches correctly in the console as well... but during processing it's getting caught by the match that comes directly _after_ and labeled as a "synopsis", which also strips the first '=' character.  Not sure what could be going wrong at this point.

**Comment by jrbostic** [comment] 2020-01-09 07:53
Okay, it's related to spaces and newlines.  We need a more robust match, I suppose.

**Comment by jrbostic** [comment] 2020-01-09 07:58
I'm not set up to put this into PR easily... but I think this matcher will fix it: `arr[i].match(/^===.*$/s)`

**Comment by superlou** [comment] 2020-01-09 23:52
@DaTedinator, see if that helps. I made the page break matcher more lenient per @jrbostic's code, though I think this is technically more lenient that the fountain spec says it should be.  @jrbostic, the trailing single-line flag wasn't supported, so this might have the same problem. Unfortunately, I still can't reproduce it on my side.

**Comment by jrbostic** [comment] 2020-01-10 01:16
It wasn't supported?  That's strange since it ran in the console fine.  Was there an exception or warning or something?

**Comment by superlou** [comment] 2020-01-10 01:18
`apm test` failed out with a syntax error.

**Comment by DaTedinator** [comment] 2020-01-10 19:42
No, looks like it's still happening.

**Comment by jrbostic** [comment] 2020-01-10 19:52
Yea, it needed that 's'.  I guess we need to work on another matcher.  Which is probably for the better if it sticks closer to the fountain spec.  Or maybe there's another way to encapsulate the regex...?

**Comment by rnkn** [comment] 2020-01-12 05:39
I hope you'll excuse the drive-by comment, but I think your issue is with your synopsis regexp `/^\s*=\s*(.+)/` which looks to be too greedy. `/^=\s*([^\n=].*)/` should do the trick. (I'd avoid permitting a leading space in case the writer wants to indent something beginning with =.)

**Comment by superlou** [comment] 2020-01-12 14:06
@rnkn I'd never fault a drive-by looking to help, thanks! I've committed the change to master. 

The weirdest part to me is that I still can't reproduce it on my end. If someone who's seeing the problem can suggest an automated test case, maybe that would help me understand what's happening.

**Comment by DaTedinator** [comment] 2020-01-12 17:49
So that change stopped it from showing up as a synopsis, but it still gets caught as a scene header, so with that change it's showing up as: 
![image](https://user-images.githubusercontent.com/29130403/72222986-5ab08e80-351f-11ea-83f5-50e07c66fb89.png)

Which, to be honest, I almost kind of really like, now that it's showing up in order, as an indicator of where page breaks are. But it's also clearly not intended. 

So with @rnkn pointing out where the root of the original issue was, it's easy to figure that this problem is in the scene heading regex: `/(^EXT\.)|(^INT\.)|(^\.[A-Z]+)|(^\s*=\s*.+)/` So when I changed it to `/(^EXT\.)|(^INT\.)|(^\.[A-Z]+)|(^\s*=\s*[^=].*)/` then yeah, it fixed the problem. That's obviously not the ideal regex to use (I imagine you'd at least want to make it [^=\n], I'm a bit rusty on my regex) but it worked for its purpose of identification.

**Comment by rnkn** [comment] 2020-01-13 04:04
@DaTedinator I’m not sure about your scene heading regexp there, as the last group will match only a synopsis. Are you sure you want a synopsis element to be matched as a scene heading?

Tangentially, the scene heading regexp will not match scene headings beginning with “I/E” or “EST” or scene headings where the writer might omit the dot. For a wider net, I’d go with something like this (untested):
~~~
/^(\.\<|(INT|EXT|EST|I/E)\.?\s)/
~~~

If helpful, this the regexp I use for Emacs:
~~~
/^(?:(?1:\.)(?2:\<(?4:.+?)(?:(?5: --? )(?6:.+)?)?)|^(?2:(?3:(?:E(?:[SX]T)|I(?:/E|NT(?:\.?/EXT)?))\.? +)(?4:.+?)?(?:(?5: --? )(?6:.+?)?)?))(?:(?7: +)(?8:#)(?9:[0-9a-z\.-]+)(?10:#))? *$/
~~~

I actually don’t use Atom, I’m just a casually interested observer.

**Comment by DaTedinator** [comment] 2020-01-13 18:30
No sorry, I wasn't saying that's what I wanted; that's what's currently in the code. I know some regex but basically everything else there is greek to me, so maybe the stuff I was saying was obvious, or the things I thought meant one thing actually meant something else.

My point was basically just, with this change now pagebreaks are getting caught as scene headings, and to me it looks like it's that regex that's catching them.

**Comment by rnkn** [comment] 2020-01-14 02:00
Ah I see. Sorry, yep I think you’re on the money.

**Comment by superlou** [comment] 2020-01-19 01:27
You're right that on the face of it, that regex looks like it's designed to  pick up a scene or synopsis and also match a page break, but I'm still confounded as to why it works on my end but not yours. I'm completely on board with everything you've both said.

Shouldn't [line 195](https://github.com/superlou/fountain-atom/blob/master/lib/fountain-outline-view.coffee#L195) evaluate truthy and skip [line 198](https://github.com/superlou/fountain-atom/blob/master/lib/fountain-outline-view.coffee#L198)?

Off-topic, these regexs need to be updated to handle international characters.

**Comment by jrbostic** [comment] 2020-03-03 18:05
@superlou Sorry I kind of dropped off on this one.  I had trouble getting the tests to run (ironically) and didn't have enough time to troubleshoot.  :(

**Comment by superlou** [comment] 2020-04-24 11:53
@DaTedinator, we might have figured something out in #99. Can you try changing your checkout settings to use Unix-style endings? On Windows, the default Git install will try to silently change line-endings to Windows-style on checkout and then silently back to the repo format during commit. I think this is messing with some of the regexes.

**Comment by DaTedinator** [comment] 2020-04-25 19:16
That fixed it immediately! I can toggle back and forth and watch the === appear and disappear in the outline.

**Comment by superlou** [comment] 2020-04-25 19:27
I'm going to close this in favor of #100.

**Closed by superlou** 2020-04-25 19:27 UTC
