### ISSUE TITLE
scene numbers not exported to PDF

### ISSUE THREAD

**Issue by brunovianna** [superlou/fountain-atom#80] opened 2018-09-10 17:20 UTC
Even with the drop-down "scene numbers" set to "both" in the settings, I get no scene numbers in the pdf.

I also tried to manually add scene numbers (using #1# in the scene header, as described in the syntax - https://fountain.io/syntax), but nothing shows up on the pdf.

In any case, congrats and thanks for the great package!

**Comment by superlou** [comment] 2018-09-10 20:32
I wonder if it is something Windows specific? I wasn't able to reproduce it
on Linux Mint. I'll see if I can try it out on a Windows machine later this
week.

**Comment by brunovianna** [comment] 2018-09-11 13:15
Actually I use mint too! uname -a:
Linux toque 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

atom 1.30.0
fountain 0.8.0

**Comment by superlou** [comment] 2018-09-11 23:09
I've got the same symptoms now. I think the tell-tale is that the contents of `configs/afterwritingConfig.json` become `{}` after generating a PDF. I have a vague memory that a recent version of Atom may have changed packages' ability modify their `packagePath`. However, I can't find a reference to that and might be completely off base there.

**Comment by superlou** [comment] 2018-09-11 23:28
@jrbostic It looks like you are trying to "flatten" an object containing nested objects into a flatter object. Is that something underscore's flatten function does? I thought it [was more for arrays](https://underscorejs.org/#flatten).

**Comment by jrbostic** [comment] 2018-09-12 06:02
@superlou I have no idea.  Doesn't make sense at the moment.  I need to get my computer set up to take a look.  Doesn't make sense that we would suddenly break from a utility function, unless the version was bumped maybe?  The only related thing that I remember that changed was we added selectable fonts for export... So, I guess I'll look there first...

**Comment by superlou** [comment] 2018-09-12 14:58
I'm going to close this issue as a duplicate of the more general #69.

**Closed by superlou** 2018-09-12 14:58 UTC
Labels: bug, duplicate
