### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by McCloudA** [superlou/fountain-atom#10] opened 2017-04-05 19:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [fountain](https://github.com/superlou/fountain-atom) package 0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/aaronmccloud/.atom/packages/fountain/lib/fountain-outline-view.coffee:101

TypeError: Cannot read property '1' of null
    at FountainOutlineView.module.exports.FountainOutlineView.getNestedChildren (/packages/fountain/lib/fountain-outline-view.coffee:101:20)
    at FountainOutlineView.module.exports.FountainOutlineView.findScenes (/packages/fountain/lib/fountain-outline-view.coffee:89:15)
    at FountainOutlineView.module.exports.FountainOutlineView.updateList (/packages/fountain/lib/fountain-outline-view.coffee:41:15)
    at /packages/fountain/lib/fountain-outline-view.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1371:25
```

### Commands

```
     -5:49.1.0 core:move-up (input.hidden-input)
     -5:48.8.0 core:move-down (input.hidden-input)
     -5:48 core:move-up (input.hidden-input)
     -5:47.5.0 core:move-left (input.hidden-input)
  6x -5:47.3.0 core:select-down (input.hidden-input)
  6x -5:46 core:backspace (input.hidden-input)
     -5:40.5.0 core:save (input.hidden-input)
  4x -4:23 fountain:toggleOutlineView (input.hidden-input)
  2x -3:32.6.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
  2x -2:41.1.0 fountain:toggleOutlineView (input.hidden-input)
  2x -0:26.6.0 editor:newline (input.hidden-input)
     -0:25.8.0 core:move-up (input.hidden-input)
  3x -0:23.8.0 core:backspace (input.hidden-input)
     -0:17.1.0 core:save (input.hidden-input)
     -0:08.3.0 editor:newline (input.hidden-input)
     -0:06.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
cobalt2-syntax 0.5.1 
fountain 0.5.3 
indent-guide-improved 1.4.12 
minimap 4.27.0 
open-recent 5.0.0 
sync-settings 0.8.1 
```

**Comment by McCloudA** [comment] 2017-04-05 19:38
BTW, I really love your Atom fountain module. Super useful and I love it!!!!!!

**Comment by superlou** [comment] 2017-04-05 21:40
@McCloudA I'm not seeing it on my end.  Can you write a list a steps to create it (and a simple fountain file that causes the issue)?  Thanks!

**Comment by jak-ashuraliev** [comment] 2017-04-09 01:23
1. Install this fountain Atom extension
2. Start writing a title that begins with a '#'
3. Sometimes (but not always - something like 30% of the time on my machine) I get that error message after typing the first '#' for a new title.

Hope this helps!

**Comment by McCloudA** [comment] 2017-04-09 01:27
Woops, was logged in as a friend. The above comment is for my machine & experiences.

BTW, I'm on a MacBook Pro (OSX 1.12.4). Hope that helps!

**Comment by superlou** [comment] 2017-04-12 22:52
@McCloudA: I've been trying to recreate this on my end with no luck.  Can you take a screenshot the next time it happens?

**Comment by McCloudA** [comment] 2017-04-13 05:08
<img width="1410" alt="screen shot 2017-04-12 at 10 06 54 pm" src="https://cloud.githubusercontent.com/assets/6210161/24990971/8085afac-1fcc-11e7-81e3-c74998577ef4.png">

**Comment by morekitsch** [comment] 2017-04-13 18:17
Looks like it's mine. I'll see what I can figure out.

**Comment by superlou** [comment] 2017-05-13 14:17
@morekitsch Any luck?  I still haven't been able to cause the issue on my installation.  Might be some kind of race condition?  Or I'm skipping a step somewhere that causes this.

**Comment by morekitsch** [comment] 2017-09-04 19:56
No luck. Sorry about the delay. I should have at least mentioned if was out
of the loop. I didn't get any results though.

**Comment by superlou** [comment] 2017-09-05 12:06
@morekitsch No problem.  Thanks for looking into it.  I'll keep my eyes open on my end, too, but if we can't recreate it in a few weeks, I'll close the issue.  We can always reopen it if it shows up again.

**Comment by jrbostic** [comment] 2017-10-12 03:50
I've just seen it too.  

It's the `match` call currently currently on ln 142.  It assumes that there is a character following the pound symbol.  And when it doesn't find one, it matches nothing and returns null.  Then an attempt to index at 1 on that result throws the error.

You can reproduce it by opening Edit > Init Script... (which has only .coffee comments on my machine)... but because it appears to be an indexing error on a null, I think you could just check if the result of calling `match` is null before processing.  Of course, I don't know what that would do to the data structure...

**Comment by jrbostic** [comment] 2017-12-05 13:53
Comment above refers to line in outline view code.

**Comment by s0u7h** [comment] 2018-01-21 16:57
Same issue for me on Windows 10 when starting a line with a hash symbol.

---

![image](https://user-images.githubusercontent.com/5218005/35196561-aaffa702-ff0e-11e7-9c2f-d7a9b85c7e5b.png)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [fountain](https://github.com/superlou/fountain-atom) package 0.7.1


### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At C:\Users\ges\.atom\packages\fountain\lib\fountain-outline-view.coffee:144

TypeError: Cannot read property '1' of null
    at FountainOutlineView.module.exports.FountainOutlineView.getNestedChildren (/packages/fountain/lib/fountain-outline-view.coffee:144:20)
    at FountainOutlineView.module.exports.FountainOutlineView.findScenes (/packages/fountain/lib/fountain-outline-view.coffee:132:15)
    at FountainOutlineView.module.exports.FountainOutlineView.updateList (/packages/fountain/lib/fountain-outline-view.coffee:54:15)
    at /packages/fountain/lib/fountain-outline-view.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:26)
    at later (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
  5x -9:36.1.0 core:backspace (input.hidden-input)
     -9:30.9.0 autocomplete-plus:confirm (input.hidden-input)
     -9:29.8.0 editor:newline (input.hidden-input)
  4x -9:27.8.0 core:backspace (input.hidden-input)
     -9:25 autocomplete-plus:confirm (input.hidden-input)
     -9:24.5.0 editor:newline (input.hidden-input)
     -5:59.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -5:57.2.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -5:54.8.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -4:07.9.0 core:backspace (input.hidden-input)
     -4:07.4.0 editor:newline (input.hidden-input)
     -4:05.5.0 core:backspace (input.hidden-input)
     -4:02.4.0 core:delete (input.hidden-input)
  2x -4:01.7.0 editor:newline (input.hidden-input)
     -4:00.8.0 core:move-up (input.hidden-input)
     -4:00.4.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
city-lights-syntax 1.1.6 
fountain 0.7.1 
pdf-view 0.62.0 
teletype 0.6.0 
```

**Comment by superlou** [comment] 2018-01-21 17:34
@s0u7h Does it happen every time you create a section?  Or only occasionally?

**Comment by jrbostic** [comment] 2018-01-21 17:41
It happens any time the outline view runs it's update function when a line like that exists in the fountain file.

**Comment by superlou** [comment] 2018-01-27 15:52
@jrbostic, I'm not too familiar with your code, so I've added a quick patch which should prevent the error.  It's not particularly elegant in that it will fail to create outline children in the condition with an "unnamed" section.  We may want to take another look at that logic down the road.

Can someone double-check that this is fixed in `master` before I publish a package update?

**Comment by jrbostic** [comment] 2018-01-27 16:41
@superlou I can have a look this evening.  However, would you be open to me looking into a better-integrated solution?  I feel like there's got to be a safer way... Like, for instance.... We display the unnamed, but add a psuedoclass to indicate on the outline that it's currently unnamed.  (Maybe appending a default value could work as well?).  I don't think that an empty title should break outline in any way.

**Comment by superlou** [comment] 2018-01-27 17:15
@jrbostic 100% agree with a safer way.  All I added was a short-circuit to the logic to prevent errors from popping up since this has been a long-standing issue.  If it looks like you'll have a nicer fix this weekend, let me know and I'll hold off on publishing until then.

**Comment by jrbostic** [comment] 2018-01-27 17:45
@superlou okay, I'll let you know.  Besides ensuring the accuracy of outline.... I'm mainly worried about messing up outline reordering, since it partially relies on the model generated in that code.

**Comment by s0u7h** [comment] 2018-01-28 10:38
New patch (on github master branch) is working well for me. No issues with section creation and outline reordering seems to work fine. Awesome!

**Comment by jrbostic** [comment] 2018-01-28 16:55
@superlou 

Okay, so, my quick fix preserves all functionality and display.  I added a piece to show text in the outline if we find an undefined section: "(untitled section)".... so it doesn't just look like a blank line.  Feel free to modify that if you don't like something about it.  Ultimately, a little css on there would help with distinguishing it in the outline, but this takes care of the basics.

See PR #52

**Comment by jrbostic** [comment] 2018-01-28 17:01
We need to do that linter this year!  :D

**Comment by superlou** [comment] 2018-01-28 17:10
That and look into using the [atom-ide outline view](https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/outline-view.md).

@s0u7h Is `master` still working with #52?  If so, I'll publish a patch and we can make new issues for fancier handling.

**Comment by superlou** [comment] 2018-01-28 17:52
Tentatively closing with release of 0.7.2.

**Closed by superlou** 2018-01-28 17:52 UTC
